// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhK0Lt8plqnkvSr6ieOLgZfdog0J9IM5Q',
    appId: '1:101211521406:web:e58b0020fa7983326a732f',
    messagingSenderId: '101211521406',
    projectId: 'ivoirelingo-app',
    authDomain: 'ivoirelingo-app.firebaseapp.com',
    storageBucket: 'ivoirelingo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhK0Lt8plqnkvSr6ieOLgZfdog0J9IM5Q',
    appId: '1:101211521406:android:e58b0020fa7983326a732f',
    messagingSenderId: '101211521406',
    projectId: 'ivoirelingo-app',
    storageBucket: 'ivoirelingo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhK0Lt8plqnkvSr6ieOLgZfdog0J9IM5Q',
    appId: '1:101211521406:ios:e58b0020fa7983326a732f',
    messagingSenderId: '101211521406',
    projectId: 'ivoirelingo-app',
    storageBucket: 'ivoirelingo-app.appspot.com',
    iosClientId: 'com.googleusercontent.apps.101211521406-v8j6c7v3j4k5s6a7s8f9g0h1i2j3k4l5',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhK0Lt8plqnkvSr6ieOLgZfdog0J9IM5Q',
    appId: '1:101211521406:ios:e58b0020fa7983326a732f',
    messagingSenderId: '101211521406',
    projectId: 'ivoirelingo-app',
    storageBucket: 'ivoirelingo-app.appspot.com',
    iosClientId: 'com.googleusercontent.apps.101211521406-v8j6c7v3j4k5s6a7s8f9g0h1i2j3k4l5',
    iosBundleId: 'com.example.myapp',
  );
}
